name: deploy_cocoapod

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Cocoapods
      run: gem install cocoapods
    
    # shortcut version
    - uses: michaelhenry/deploy-to-cocoapods-github-action@1.0.10
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}